version: '3'

services:
  Nginx:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  express_1:
    build:
      context: ./src
    container_name: express_1
    environment:
      - NodeJS_HOST=0.0.0.0
      - NodeJS_PORT=8001
      - MYSQL_HOST=db
      - MYSQL_USER=tilog
      - MYSQL_PASSWORD=Testpassword
      - MYSQL_DATABASE=tilog
    expose:
      - "8001"
  db:
    image: mysql:5.7
    container_name: Database
    environment:
      - MYSQL_ROOT_PASSWORD=Testpassword
      - MYSQL_USER=tilog
      - MYSQL_PASSWORD=Testpassword
      - MYSQL_DATABASE=tilog
    volumes:
      - "./docker/mysql/mysql-init-files/:/docker-entrypoint-initdb.d/"
      - "./docker/mysql/mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"