version: '3'

services:
  Nginx:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  express_1:
    build:
      context: ./src
    container_name: express_1
    ports:
      - "8001"
