version: "3"

services:
  Database_Mysql:
    image: mysql:5.7
    container_name: Database_Mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=TILog
      - MYSQL_USER=TILog
      - MYSQL_PASSWORD=1q2w3e4r
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - LC_ALL=C.UTF-8
    volumes:
      - "./docker/mysql/mysql-init-files/:/docker-entrypoint-initdb.d/"
      - "./docker/mysql/mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  Redis:
    image: redis:latest
    container_name: Redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --port 6379
